classmanager/config/routes.rb
Hc::Application.routes.draw do
  root :to => "main#index"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :departments, :classbjs, :students, :events, :regulations

end

classmanager/app/models/classbj.rb
class Classbj < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  belongs_to :department
  has_many :students

  def avg_score
    return 0 if self.num == 0
    self.score / self.num
  end

  def rank_department
    Classbj.where("department_id = :dpt AND score > :s", 
                  dpt: self.department, s: self.score).count + 1
  end

  def rank_global
    Classbj.where("score > #{self.score}").count + 1
  end
end

classmanager/app/models/department.rb
class Department < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true

  def num_of_class
    return self.classes.length
  end

  def avg_score
    return 0 if self.num_of_class <= 0
    self.score / self.num_of_class
  end

  def score
    self.classes.sum {|x| x.avg_score}
  end

  def classes
    return Classbj.where("department_id == #{self.id}")
  end

end

classmanager/app/models/event.rb
#encoding:utf-8
class Event < ActiveRecord::Base
  belongs_to :student
  belongs_to :regulation
  
  after_create do |e|
    c = e.student.classbj
    c.score += e.score!
    c.save
  end

  def description
    self.regulation.name
  end

  def score!
    self.regulation.score
  end 

  def score
    self.regulation.score.abs
  end

  def type
    if regulation.score > 0 
      return true
    else
      return false
    end
  end
end

classmanager/app/models/regulation.rb
class Regulation < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
end

classmanager/app/models/student.rb
class Student < ActiveRecord::Base
  validates :No, :presence => true, :uniqueness => true
  belongs_to :classbj
  has_many :events

  after_create do |s|
    self.classbj.num += 1
    self.classbj.save
  end

  def score
    self.events.all.sum { |x| x.regulation.score }
  end

  def week_score
    self.events.where("date > 0").sum { |x| x.regulation.score }
  end
end

classmanager/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

classmanager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

classmanager/app/controllers/classbjs_controller.rb
class ClassbjsController < ApplicationController
  def show
    c = Classbj.find(params[:id])
    @students = c.students
    @classname = c.name
    @departname = c.department.name
    @departurl = department_path(c.department)

    @global_rank = c.rank_global
    @depart_rank = c.rank_department

    @score = c.score
    @avg_score = c.avg_score
  end
end

classmanager/app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def show
    d = Department.find(params[:id])
    @departname = d.name
    @classes = d.classes.sort {|a,b| a.rank_department <=> b.rank_department}
  end
end

classmanager/app/controllers/events_controller.rb
class EventsController < ApplicationController
end

classmanager/app/controllers/main_controller.rb
#encoding:utf-8
class MainController < ApplicationController
  def index
    @events = Event.order("date").limit(10)
    @classes = Classbj.all()
    @departments = Department.all().sort {|a,b| a.avg_score <=> b.avg_score}

    @chart_department = self.chart1
    @chart_avg = self.chart2

  end

  protected
  def chart1
    data = @departments.map {|x| [x.name, x.score]}
    LazyHighCharts::HighChart.new('pie') do |f|
      f.title({:text => "院校累计分数贡献榜"})
      f.series(:type=>'pie', :name=>'累计贡献', :data=>data)
    end
  end
  def chart2
    d1,d2 = [[],[]]
    @departments.each {|x| d1.push x.name; d2.push x.avg_score}
    LazyHighCharts::HighChart.new('graph') do |f|
      f.title({:text => "院校人均分数排行"})
      f.options[:chart][:defaultSeriesType] = "column"
      f.options[:legend][:enabled] = false
      f.options[:xAxis][:categories] = d1
      f.series(:name=>'平均分', :data=>d2)
    end
  end
end

classmanager/app/controllers/regulations_controller.rb
class RegulationsController < ApplicationController
end

classmanager/app/controllers/students_controller.rb
#encoding:utf-8
class StudentsController < ApplicationController
  def show
    s = Student.find(params[:id])
    @classname = s.classbj.name
    @classurl = classbj_path(s.classbj)
    @departname = s.classbj.department.name
    @departurl = department_path(s.classbj.department)
    @studentname = s.name

    @score = s.score

    @global_rank = 14
    @depart_rank = 5

    @events = s.events.order("date DESC")
    @chart_month = self.month
    @chart_year = self.year
  end

  protected
  def week_score(year, month, day)
    s_add = []
    s_minus = []
    tmp1 = 0
    tmp2 = 0
    (1..day).each do |d|
      d = Date.new(year, month, d)
      es = @events.select { |e| e.date >= d && e.date <= d.succ}
      es.each do |e|
        if e.score! > 0
          tmp1 += e.score
        else
          tmp2 += e.score
        end
      end
      s_add.push(tmp1)
      s_minus.push(tmp2)
    end
    s_avg = s_add.zip(s_minus).map {|x| x[0]-x[1]}
    return [s_add, s_minus, s_avg]
  end
  def month_score(year, month)
    tmp = []
    (1..month).each do |m| 
      s = week_score(year, m, 28)
      tmp.push [s[0][-1], s[1][-1], s[2][-1]]
    end
    xx = [[],[],[]]
    tmp.each do |m|
      xx[0].push m[0]
      xx[1].push m[1]
      xx[2].push m[2]
    end
    return xx
  end

  def month
    LazyHighCharts::HighChart.new('graph') do |f|
      f.title({:text => "本月趋势图"})
      f.options[:xAxis][:categories] = (1..31).map {|x| x.to_s }
      f.options[:chart][:defaultSeriesType] = "area"
      today = Date.today
      s_add, s_minus, s_avg = week_score(today.year, today.month, today.day)
      f.series(:name=>'加分', :data=>s_add)
      f.series(:name=>'减分', :data=>s_minus)
      f.series(:name=>'平均', :type=>'spline', :data=>s_avg)
    end
  end

  def year
    LazyHighCharts::HighChart.new('graph') do |f|
      f.title({ :text=>"年度趋势图"})
      f.options[:xAxis][:categories] = ['一月', '二月', '三月', '四月', '五月','六月', 
        '七月', '八月', '九月', '十月', '十一月','十二月']
      today = Date.today
      s_add, s_minus, s_avg = month_score(today.year, today.month)
      f.series(:type=> 'column',:name=> '加分',:data=> s_add)
      f.series(:type=> 'column',:name=> '减分',:data=> s_minus)
      f.series(:type=> 'spline',:name=> '平均', :data=> s_avg)
    end
  end
end

classmanager/app/helpers/application_helper.rb
module ApplicationHelper
end

classmanager/app/helpers/classbjs_helper.rb
module ClassbjsHelper
end

classmanager/app/helpers/departments_helper.rb
module DepartmentsHelper
end

classmanager/app/helpers/events_helper.rb
module EventsHelper
end

classmanager/app/helpers/main_helper.rb
module MainHelper
end

classmanager/app/helpers/regulations_helper.rb
module RegulationsHelper
end

classmanager/app/helpers/students_helper.rb
module StudentsHelper
end

classmanager/app/views/classbjs/show.html.erb
<% content_for :breadcrumb do %>
  <ul class="breadcrumb">
  <span>当前位置:</span>
    <li><a href="/">主页</a><span class="divider">/</span></li>
    <li><a href=<%=@departurl%>><%=@departname%></a><span class="divider">/</span></li>
    <li><a href="#"><big><%=@classname%></big></a><span class="divider">/</span></li>
  </ul>
<% end %>
<div class="row">
  <div class="span8">
    <table class="table">
      <thead><h3>班级内部情况<small>(点击成员名查看详情)</small></h3></thead>
      <tr>
        <th>成员</th> <th>性别</th> <th>学号</th> <th>个人总分</th>
      </tr>
      <tbody>
        <%- @students.each do |s| %>
            <tr>
              <td><a href=<%=student_path(s)%>><%= s.name %></a></td>
              <td><%= s.sex %></td>
              <td><%= s.No %></td>
              <td><%= s.score %></td>
            </tr>
        <%- end %>
      </tbody>
    </table>
  </div>

  <div class="span4">
    <table class="table">
      <thead><h3>校内情况</h3></thead>
      <tr>
        <th>全校排名</th> <th>院内排名</th> <th>班级总分</th>
      </tr>
      <tbody>
        <tr>
          <td><%= @global_rank %></td>
          <td><%= @depart_rank %></td>
          <td><%= @score %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

classmanager/app/views/departments/show.html.erb
<% content_for :breadcrumb do %>
  <ul class="breadcrumb">
    <span>当前位置:</span>
    <li><a href="/">主页</a><span class="divider">/</span></li>
    <li><a href="#"><big><%=@departname%></big></a><span class="divider">/</span></li>
  </ul>
<% end %>

<ul>
<% @classes.each do |c| %>
  <div class="class_box">
    <ul>
      <li><b>班级名称:</b><span><a href=<%=classbj_path(c)%>><%=c.name%></a></span></li>
      <li><b>班级人数:</b><span><%=c.num%></span></li>
      <li><b>人均分数:</b><span><%=c.avg_score%></span></li>
      <li><b>累计总分:</b><span><%=c.score%></span></li>
      <li><b>院内排名:</b><span><%=c.rank_department%></span></li>
      <li><b>全校排名:</b><span><%=c.rank_global%></span></li>
    </ul>
  </div>
<% end %>
</ul>

classmanager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>班级管理系统-湖北经济学院</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body style="padding-top:0">
    <div class="container">
      <div class="nav">
        <h1>湖北经济学院班级管理系统</h1>
        <%= yield :breadcrumb %>
      </div>
      <%= yield %>
      <div id="Footer">
        本系统为湖北经济学院信管学院计算机科学与技术专业S1021班<span href="" id="author" rel="tooltip" title="浮肿大神"><b>胡辰</b></span>同学毕业设计作品
        <span class="pull-right"><a href="/admin">后台登录</a></span>
      </div>
    </div>
    <script>
      $('#author').tooltip();
    </script>
  </body>
</html>

classmanager/app/views/main/index.html.erb
<% content_for :breadcrumb do %>
  <ul class="breadcrumb">
  <span>当前位置:</span>
    <li><a href="/">主页</a><span class="divider">/</span></li>
    <li><big>最新动态</big></li>
  </ul>
<% end %>

<div class="row">
  <div class="span9">
    <div class="row">
    <div class="span5">
      <%= high_chart("chartdepartment", @chart_department)%>
    </div>
    <div class="span4">
      <%= high_chart("chartavg", @chart_avg) do |c| %>
        <%= "options.xAxis.labels = {}" %>
        <%= "options.xAxis.labels.enabled = false " %>
      <% end %>
    </div>
  </div>

    <div id="news">
      <ul>
        <% @events.each do |e| %>
          <%- if e.type -%>
            <li class="alert alert-success">
              表扬:
              (<%= e.student.classbj.department.name %>)
              <span>
                <a href=<%=classbj_path(e.student.classbj)%>><%= e.student.classbj.name %></a>
              </span>班的
              <span><a href=<%=student_path(e.student)%>><%= e.student.name %></a></span>同学
              因为"<b><%= e.description %></b>"特加<span><%= e.score %></span>分以资鼓励.
            </li>
          <%- else -%>
            <li class="alert alert-error">
              批评: 
              (<%= e.student.classbj.department.name %>)
              <span>
                <a href=<%=classbj_path(e.student.classbj)%>><%= e.student.classbj.name %></a>
              </span>班的
              <span><a href=<%=student_path(e.student)%>><%= e.student.name %></a></span>同学
              因为"<%= e.description %>"特对其进行减<span><%= e.score %></span>分的处罚.
            </li>
          <%- end -%>
        <%- end -%>
      </ul>
    </div>
  </div>



  <div class="span3">
    <div>
      <h2>院系列表</h2>

      <%- @departments.each do |d| -%>
        <div>
          <a href=<%=department_path(d)%>><span class="icon-home"></span></a>
          <button class="btn btn-danger" <%-if d.num_of_class != 0%>data-toggle="collapse" data-target="#clist<%=d.id%>"<%-end-%>
            >
            <%=  d.name %>(<%= d.num_of_class %>)
          </button>
          <%-if d.num_of_class != 0-%>
            <div id="clist<%=d.id%>" class="collapse in">
              <ul>
                <%- d.classes.each do |c| %>
                  <li><a href=<%= classbj_path(c)%>><%= c.name %></a></li>
                <%- end %>
              </ul>
            </div>
          <%-end-%>
        </div>
      <%- end -%>
    </div>
  </div>
</div>
<script>
  $(".collapse").collapse();
</script>

classmanager/app/views/students/show.html.erb
<% content_for :breadcrumb do %>
  <ul class="breadcrumb">
    <span>当前位置:</span>
    <li><a href="/">主页</a><span class="divider">/</span></li>
    <li><a href=<%=@departurl%>><%=@departname%></a><span class="divider">/</span></li>
    <li><a href=<%=@classurl%>><%=@classname%></a><span class="divider">/</span></li>
    <li><a href="#"><big><%=@studentname%></big></a><span class="divider">/</span></li>
  </ul>
<% end %>

<span>累积得分:<%=@score%></span>
<div class="row">
  <div class="span4">
    <%= high_chart("chartmonth", @chart_month)%>
  </div>

  <div class="span7">
    <%= high_chart("chartyear", @chart_year)%>
  </div>
</div>

<table class="table">
  <thead><h3>事件详情表</h3></thead>
  <tbody>
    <tr>
      <th>时间</th> <th>事件</th> <th>影响分数</th> <th>备注</th>
    </tr>
    <%- @events.each do |e| %>
      <tr>
        <th><%= e.date %></th>
        <th><%= e.description %></th>
        <th><%= e.score! %></th>
        <th><%= e.remark%></th>
      </tr>
    <%- end %>
  </tbody>
</table>